version: "3.8"

services:
  python_app:
    container_name: py-aurora-app
    build:
      context: ./python_app
    ports:
      - 80:5000
    networks:
      - aurora_network

networks:
  aurora_network:
